/**
 * Open Wonderland
 *
 * Copyright (c) 2010, Open Wonderland Foundation, All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * The Open Wonderland Foundation designates this particular file as
 * subject to the "Classpath" exception as provided by the Open Wonderland
 * Foundation in the License file that accompanied this code.
 */
package org.jdesktop.wonderland.modules.corenpc.client.cell;

import com.jme.scene.Spatial.CullHint;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.mtgame.processor.WorkProcessor.WorkCommit;
import org.jdesktop.wonderland.client.jme.SceneWorker;
import org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer.ImiPickGeometry;
import org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer.ImiPickGeometry.PickBox;
import org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer.WlAvatarCharacter;

/**
 *
 * @author jkaplan
 */
class PickGeometryEditor extends javax.swing.JFrame {
    private static final Logger logger =
            Logger.getLogger(PickGeometryEditor.class.getName());

    private final ImiPickGeometry geometry;
    private PickBox box;
    private boolean active = false;

    /** Creates new form PickGeometryEditor */
    public PickGeometryEditor(ImiPickGeometry geometry, PickBox box,
                              WlAvatarCharacter avatar)
    {
        this.geometry = geometry;
        this.box = box;

        initComponents();

        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for (String attachPoint : avatar.getSkeleton().getJointNames()) {
            dcbm.addElement(attachPoint);
        }
        jointCB.setModel(dcbm);

        xS.setValue(box.getCenter().x);
        yS.setValue(box.getCenter().y);
        zS.setValue(box.getCenter().z);

        xSizeS.setValue(box.getXExtent());
        ySizeS.setValue(box.getYExtent());
        zSizeS.setValue(box.getZExtent());

        jointCB.setSelectedItem(box.getJointName());

        active = true;
    }

    private void update() {
        // don't make changes while we are initializing
        if (!active) {
            return;
        }

        SceneWorker.addWorker(new WorkCommit() {
            public void commit() {
                doUpdate();
            }
        });
    }

    private void doUpdate() {
        box.detach();

        String joint = (String) jointCB.getSelectedItem();

        float x = (Float) xS.getValue();
        float y = (Float) yS.getValue();
        float z = (Float) zS.getValue();

        float xSize = (Float) xSizeS.getValue();
        float ySize = (Float) ySizeS.getValue();
        float zSize = (Float) zSizeS.getValue();

        boolean visible = visibleCB.isSelected();

        box = new PickBox(joint, x, y, z, xSize, ySize, zSize);
        box.attach(geometry);

        if (visible) {
            box.setCullHint(CullHint.Inherit);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        xS = new javax.swing.JSpinner();
        yS = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        zS = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xSizeS = new javax.swing.JSpinner();
        ySizeS = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        zSizeS = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        visibleCB = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jointCB = new javax.swing.JComboBox();

        jLabel1.setText("X");

        xS.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.01f)));
        xS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xSStateChanged(evt);
            }
        });

        yS.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.99f), null, null, Float.valueOf(0.01f)));
        yS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ySStateChanged(evt);
            }
        });

        jLabel2.setText("Y");

        zS.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.01f)));
        zS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zSStateChanged(evt);
            }
        });

        jLabel3.setText("Z");

        jLabel4.setText("Size");

        xSizeS.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.4f), null, null, Float.valueOf(0.01f)));
        xSizeS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xSizeSStateChanged(evt);
            }
        });

        ySizeS.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.95f), null, null, Float.valueOf(0.01f)));
        ySizeS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ySizeSStateChanged(evt);
            }
        });

        jLabel5.setText("Size");

        zSizeS.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.1f), null, null, Float.valueOf(0.01f)));
        zSizeS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zSizeSStateChanged(evt);
            }
        });

        jLabel6.setText("Size");

        visibleCB.setText("Visible");
        visibleCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleCBActionPerformed(evt);
            }
        });

        jLabel7.setText("Attach to:");

        jointCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jointCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jointCBActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .add(18, 18, 18)
                                .add(yS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .add(18, 18, 18)
                                .add(xS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(xSizeS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ySizeS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(18, 18, 18)
                        .add(zS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(zSizeS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(visibleCB)
                    .add(layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jointCB, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jointCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(xSizeS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(xS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(yS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(ySizeS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(zS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(zSizeS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .add(26, 26, 26)
                .add(visibleCB)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xSStateChanged
        update();
    }//GEN-LAST:event_xSStateChanged

    private void ySStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ySStateChanged
        update();
    }//GEN-LAST:event_ySStateChanged

    private void zSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zSStateChanged
        update();
    }//GEN-LAST:event_zSStateChanged

    private void xSizeSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xSizeSStateChanged
        update();
    }//GEN-LAST:event_xSizeSStateChanged

    private void ySizeSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ySizeSStateChanged
        update();
    }//GEN-LAST:event_ySizeSStateChanged

    private void zSizeSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zSizeSStateChanged
        update();
    }//GEN-LAST:event_zSizeSStateChanged

    private void visibleCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleCBActionPerformed
        update();
    }//GEN-LAST:event_visibleCBActionPerformed

    private void jointCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jointCBActionPerformed
        update();
    }//GEN-LAST:event_jointCBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jointCB;
    private javax.swing.JCheckBox visibleCB;
    private javax.swing.JSpinner xS;
    private javax.swing.JSpinner xSizeS;
    private javax.swing.JSpinner yS;
    private javax.swing.JSpinner ySizeS;
    private javax.swing.JSpinner zS;
    private javax.swing.JSpinner zSizeS;
    // End of variables declaration//GEN-END:variables

}
